name: Test Docker Image

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Workflow Docker'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  smoketest:
    name: smoketest
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull xbgmsharp/timescaledb-postgis

      - name: Install psql
        run: sudo apt install postgresql-client

      - name: Run smoke test
        run: |
          set -eu
          export PGHOST=localhost
          export PGUSER=postgres
          export PGPASSWORD=test1234
          docker container stop smoketest-image || true
          docker container rm smoketest-image || true
          docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=${PGPASSWORD} --name smoketest-image xbgmsharp/timescaledb-postgis
          sleep 10
          for _ in {1..120}
          do
            if [ -z "$(docker container ls -q --filter name=smoketest-image)" ]
            then
              echo "Smoketest container is not running"
              exit 1
            fi
            if psql -c "select 1"
            then
              echo "Test PostgreSQL"
              psql -c "SELECT version();"
              ls -lh tests/extensions_test/test*.sh
              for f in tests/extensions_test/test*.sh; do
                if ! bash "$f"; then exit 1; fi
              done
              break
            fi
            sleep 1
          done
          if ! psql -c "select 1"
          then
            echo "Cannot connect to PostgreSQL"
            exit 1
          fi

      - name: Show the logs
        if: always()
        run: |
          docker logs smoketest-image